### ISSUE TITLE
Drizzle ORM + SQLite + Bun.JS does not work

### ISSUE THREAD

**Issue by otekdo** [drizzle-team/drizzle-bun#2]
I am trying to use Drizzle with SQLite on BUN, is not possible. 
It does not migrate the schema to the `database file`

**Repository Link:** https://github.com/otekdo/bunjs-drizzle-sqlite

`generate` command works
```
$ bun drizzle-kit generate:sqlite
drizzle-kit: v0.19.13
drizzle-orm: v0.28.5

No config path provided, using default 'drizzle.config.ts'
Reading config file '/home/nexus/Documents/apps/bun-drizzle-sqlite/drizzle.config.ts'
1 tables
users 8 columns 0 indexes 0 fks

[✓] Your SQL migration file ➜ src/db/migrations/0000_bizarre_morlocks.sql 🚀
```

`push` command does not works
```$ bun drizzle-kit push:sqlite
No config path provided, using default path
Reading config file '/home/nexus/Documents/apps/bun-drizzle-sqlite/drizzle.config.ts'
drizzle-kit: v0.19.13
drizzle-orm: v0.28.5

/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/bindings/bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/build/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/compiled/18.17.1/linux/x64/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/lib/binding/node-v108-linux-x64/better_sqlite3.node
    at bindings (/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/bindings/bindings.js:126:9)
    at new Database (/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/lib/database.js:48:64)
    at _createClient (/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/drizzle-kit/index.cjs:43506:14)
    at _createClient4 (/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/drizzle-kit/index.cjs:51839:12)
    at createClient (/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/drizzle-kit/index.cjs:51834:10)
    at connectToSQLite (/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/drizzle-kit/index.cjs:51888:13)
    at Command.<anonymous> (/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/drizzle-kit/index.cjs:53433:28) {
  tries: [
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/compiled/18.17.1/linux/x64/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/home/nexus/Documents/apps/bun-drizzle-sqlite/node_modules/better-sqlite3/lib/binding/node-v108-linux-x64/better_sqlite3.node'
  ]
}

Node.js v18.17.1
error: "drizzle-kit" exited with code 1 (SIGHUP)
error: script "push" exited with code 1 (SIGHUP)
```

It does not matter which driver is set on drizzle config file, issue still happens
`libsql` or `better-sqlite`

Environment
```
Bun: v0.8.1
drizzle-kit: v0.19.13
drizzle-orm: v0.28.5
```

**Comment by otekdo** [comment]
Fixed on https://github.com/drizzle-team/drizzle-orm/issues/1179
